# Fator de Visão de Céu a partir do LiDAR

Podemos determinar o Fator de Visão de céu, ou Sky View Factor diretamente do LiDAR sem gerar um raster.
Para fins de performance podemos reduzir a densidade de pontos para cerca de 1 metro de resolução e a partir de cada ponto de Ground calcular a coordenada astronômica (Azimute e Altura) e a distância linear para cada ponto classificados como edificação.

Para esse primeiro experimento vamos apenas usar uma folha SCM, sabendo que inerferências para visão de céu podem se estender muito além dos limites das dimensões de uma folha SCM.

In [1]:
import pdal

In [2]:
%load_ext autotime

In [3]:
pipeline="""{
  "pipeline": [
    {
        "type": "readers.las",
        "filename": "arquivos/MDS/MDS_3314-231.laz"
    },
    {
        "type": "filters.sample",
        "radius": 1
    }
  ]
}"""

In [4]:
r = pdal.Pipeline(pipeline)
r.validate()
r.execute()
arrays = r.arrays

In [5]:
len(arrays[0])

471962

In [6]:
arrays[0][0]

(333499.29, 7395564.35, 735.34, 18, 1, 1, 0, 0, 6, -14., 17, 6, 356569.36606547)

In [7]:
r.schema

{'schema': {'dimensions': [{'name': 'X', 'size': 8, 'type': 'floating'},
   {'name': 'Y', 'size': 8, 'type': 'floating'},
   {'name': 'Z', 'size': 8, 'type': 'floating'},
   {'name': 'Intensity', 'size': 2, 'type': 'unsigned'},
   {'name': 'ReturnNumber', 'size': 1, 'type': 'unsigned'},
   {'name': 'NumberOfReturns', 'size': 1, 'type': 'unsigned'},
   {'name': 'ScanDirectionFlag', 'size': 1, 'type': 'unsigned'},
   {'name': 'EdgeOfFlightLine', 'size': 1, 'type': 'unsigned'},
   {'name': 'Classification', 'size': 1, 'type': 'unsigned'},
   {'name': 'ScanAngleRank', 'size': 4, 'type': 'floating'},
   {'name': 'UserData', 'size': 1, 'type': 'unsigned'},
   {'name': 'PointSourceId', 'size': 2, 'type': 'unsigned'},
   {'name': 'GpsTime', 'size': 8, 'type': 'floating'}]}}

## Importando dados para Pandas

In [8]:
import pandas as pd

In [9]:
df = pd.DataFrame(arrays[0])

In [10]:
df

X           Y       Z  Intensity  ReturnNumber  \
0       333499.29  7395564.35  735.34         18             1   
1       333499.23  7395565.79  735.41         18             1   
2       333499.20  7395566.79  735.25         15             1   
3       333499.15  7395568.21  735.37         14             1   
4       333499.10  7395569.68  735.30         17             1   
...           ...         ...     ...        ...           ...   
471957  333523.36  7395570.78  735.52          2             1   
471958  333521.03  7395570.91  731.07          5             1   
471959  333520.96  7395571.00  732.50          8             1   
471960  333521.09  7395571.84  731.83         18             1   
471961  333520.95  7395571.91  729.86         18             1   

        NumberOfReturns  ScanDirectionFlag  EdgeOfFlightLine  Classification  \
0                     1                  0                 0               6   
1                     1                  0                 0               6   
2                     1                  0                 0               6   
3                     1                  0                 0               6   
4                     1                  0                 0               6   
...                 ...                ...               ...             ...   
471957                2                  1                 0              19   
471958                1                  1                 0               6   
471959                1                  1                 0               6   
471960                1                  1                 0               6   
471961                1                  0                 0               6   

        ScanAngleRank  UserData  PointSourceId        GpsTime  
0               -14.0        17              6  356569.366065  
1               -14.0        17              6  356569.366090  
2               -14.0        17              6  356569.366105  
3               -14.0        17              6  356569.366129  
4               -15.0        17              6  356569.366153  
...               ...       ...            ...            ...  
471957           13.0        40              6  363044.324524  
471958           13.0        40              6  363044.342732  
471959           13.0        40              6  363044.342740  
471960           13.0        40              6  363044.360909  
471961           13.0        40              6  363044.364125  

[471962 rows x 13 columns]

In [11]:
df.Classification.unique()

array([ 6, 20,  2, 19,  5,  9], dtype=uint8)

## Calculando o Azimute entre dois pontos

Suponhamos que fossemos calcular o azimute para cada ponto poderíamos fazer utilizando a seguinte função

In [12]:
import math

def Az(x1,y1,x2,y2):
    deg = math.degrees(math.atan2((x2 - x1),(y2 - y1)))
    if (deg < 0):
        deg += 360.0
    return deg

In [13]:
Az(1, 1, 1, 0)

180.0

## Calculando a Altura ou Elevação do ponto em relação ao Zenite

Da mesma forma poderíamos calcular a Altura/Elevação para cada um dos pontos usando a seguinte função

In [14]:
from scipy.spatial import distance

ModuleNotFoundError: No module named 'scipy'

In [ ]:
## Calculando altura
def altura_graus(x1, y1, z1, x2, y2, z2):
    altura = z2 - z1
    distancia = distance.euclidean([x1, y1], [x2, y2])
    return math.degrees(math.atan2(altura, distancia))

altura_graus(0,0,0,1,1,1)

## Gerando pontos x,y,z 

Apesar de termos diversas dimensões disponíveis para os calculos vamos nos ater em X, Y e Z e na Classificação para poder agrupar o que é Ground e o Que é edificação

In [16]:
df_ground = pd.DataFrame.from_records(df[df.Classification == 2][['X', 'Y', 'Z']].head(1000))

In [17]:
df_ground

X           Y       Z
0    333499.25  7395550.72  724.76
1    333499.14  7395553.60  724.86
2    333498.88  7395560.92  724.87
3    333498.72  7395562.04  725.02
4    333498.36  7395551.34  724.89
..         ...         ...     ...
995  333126.05  7395522.71  728.50
996  333125.87  7395511.48  728.59
997  333125.28  7395506.59  728.60
998  333125.02  7395513.41  728.59
999  333124.77  7395520.19  728.69

[1000 rows x 3 columns]

In [18]:
df_building = pd.DataFrame.from_records(df[df.Classification == 6][['X', 'Y', 'Z']])
df_building = df_building.rename(columns={'X':'X1', 'Y':'Y1', 'Z':'Z1'})

In [19]:
df_building

X1          Y1      Z1
0       333499.29  7395564.35  735.34
1       333499.23  7395565.79  735.41
2       333499.20  7395566.79  735.25
3       333499.15  7395568.21  735.37
4       333499.10  7395569.68  735.30
...           ...         ...     ...
300787  333520.79  7395569.75  730.02
300788  333521.03  7395570.91  731.07
300789  333520.96  7395571.00  732.50
300790  333521.09  7395571.84  731.83
300791  333520.95  7395571.91  729.86

[300792 rows x 3 columns]

## Calculando o Azimute com Matriz de pontos

Portanto agora que temos os pontos de origem e os pontos alvo podemos calcular o Azimute. Porém se fizermos isso ponto a ponto não vamos usar os recursos computacionais de vetorização que promovem grande eficiência computacional.
Ainda não será exatamente essa função que vamos utilzar em produção, mas para fins didáticos e de aprendizado vamos mante-las.

In [20]:
import numpy as np

def np_az(nd_building, nd_ground):
    delta_x = nd_building[:, 0] - nd_ground[0, 0]
    delta_y = nd_building[:, 1] - nd_ground[0, 1]
    degree = np.arctan2(delta_x, delta_y) * 180 / np.pi
    degree[np.less(degree, 0)] += 360.0
    return degree

In [21]:
## Gerando dados de teste
test_ground = np.array([[0.,0.,0.], [1.,1.,1.]])
test_building = np.array([[0.,2.,2.], [2.,0,2.], [0.,-2.,2.], [-2.,0,18787.], [-2.,9899.,0.1]])

In [22]:
az = np_az(test_building, test_ground)
az

array([  0.        ,  90.        , 180.        , 270.        ,
       359.98842393])

## Calculando a altura/elevação com matriz de pontos

Da mesma forma vamos fazer com a altura/elevação

In [23]:
## Calculando altura/elevação

from scipy.spatial import distance

def np_altura(nd_building, nd_ground):
    altura = nd_building[:, 2] - nd_ground[0, 2]
    distancia = np.sqrt(np.sum((nd_building[:, [0,1]] - nd_ground[0, [0,1]])**2, axis=1))
    return np.arctan2((nd_building[:, 2] - nd_ground[0, 2]), distancia) * 180 / np.pi

In [24]:
altura = np_altura(test_building, test_ground)
altura

array([4.50000000e+01, 4.50000000e+01, 4.50000000e+01, 8.99939005e+01,
       5.78803701e-04])

In [25]:
nd_coordenadas = np.array([az, altura])
nd_coordenadas.transpose().shape

(5, 2)

## Utilizando os dados de Building

As funcões de calculo de Azimute e Altura/Elevação produzidas até agora aqui nesse NoteBook precisam ser iteradas sobre cada linha de ponto de ground. Portanto precisamos refatorar essas funções para trabalhar e iterar sobre cada um dos pontos utilizando o potencial computacional do NumPy, ou seja, trabalhando com vetorização.

In [26]:
nd_building = df_building.to_numpy()
nd_ground = df_ground.to_numpy()

In [27]:
len(nd_building)

300792

In [28]:
#def calc_svf(nd_building, nd_ground):
#    az = np_az(nd_building, nd_ground)
#    altura = np_altura(nd_building, nd_ground)
#    coordenadas = np.array([az, altura])
#    return coordenadas.transpose()

In [29]:
#calc_svf(nd_building, nd_ground)

### Refatorando as funções de Azimute e Altura para trabalhar com o vetorização de Ground e Building

Para fins computacionais e menos iterações de laço que tendem a não ser tão eficientes, vamos tentar usar os recursos de vetorização e evitar o laço repetitivo

In [30]:
# def np_coordenadas(nd_building, nd_ground):
#     n2d_ground_z = nd_ground[:, 2].reshape(-1, 1)
#     n2dt_building_z = nd_building[:, 2].reshape(-1, 1).transpose()
    
#     nd_altura = np.subtract(n2dt_building_z, n2d_ground_z)
    
#     n2d_ground_x = nd_ground[:, 0].reshape(-1, 1)
#     n2dt_building_x = nd_building[:, 0].reshape(-1, 1).transpose()
#     nd_delta_x = np.subtract(n2dt_building_x, n2d_ground_x)
    
#     n2d_ground_y = nd_ground[:, 1].reshape(-1, 1)
#     n2dt_building_y = nd_building[:, 1].reshape(-1, 1).transpose()
#     nd_delta_y = np.subtract(n2dt_building_y, n2d_ground_y)
    
#     nd_distancia = np.hypot(nd_delta_x, nd_delta_y)
    
#     nd_elevacao = np.degrees(np.arctan2(nd_altura, nd_distancia))
#     #nd_elevacao[np.less(nd_elevacao, 0.)] += 360.0
    
#     nd_azimute = np.arctan2(nd_delta_x, nd_delta_y) * 180 / np.pi
#     nd_azimute[np.less(nd_azimute, 0.)] += 360.0
    
#     return nd_azimute, nd_elevacao

In [31]:
## Gerando dados de teste
test_ground = np.array([[0.,0.,0.], [-1.,-1.,-1.], [1.,1.,1.]], dtype='float32')
test_building = np.array([[0.,2.,2.], [2.,0,2.], [0.,-2.,2.], [-2.,0,18787.], [-2.,9899.,0.1]], dtype='float32')

In [32]:
# azimute, elevacao = \
# np_coordenadas(nd_building, nd_ground)
# print("Distância: ")
# print(elevacao.shape)
# print(elevacao.size)
# print("Elevacao: ")
# print(azimute.shape)
# print(azimute.size)

In [33]:
# nd_coordenadas = np.stack((azimute, elevacao), axis=1)

In [34]:
# nd_coordenadas

### Menos linhas, mais legibilidade, talvez mais eficiência

Podemos ainda refatorar o código acima e reduzir algumas linhas de código, trabalhando desde o começo com 3 dimensões. Isso ainda pode acarretar alguma melhora na performance computacional mas não é a intenção por enquanto.

In [36]:
def np_coordenadas(nd_building, nd_ground):
    n2d_ground = nd_ground[:, :].reshape(-1, 3).astype('float32')
    n2d_ground = n2d_ground.reshape(-1, 3, 1)

    n2dt_building = nd_building[:, :].reshape(-1, 3).astype('float32')
    n2dt_building = n2dt_building.reshape(-1, 3, 1).transpose()

    nd_delta = np.subtract(n2dt_building, n2d_ground)
    
    nd_altura = nd_delta[:,2,:]
    
    nd_distancia = np.hypot(nd_delta[:,0,:], nd_delta[:,1,:])
    
    nd_elevacao = np.degrees(np.arctan2(nd_altura, nd_distancia))
    nd_elevacao[np.less(nd_elevacao, 0.)] += 360.0
    
    nd_azimute = np.arctan2(nd_delta[:,1,:], nd_delta[:,0,:]) * 180 / np.pi
    nd_azimute[np.less(nd_azimute, 0.)] += 360.0
    
    return nd_azimute, nd_elevacao

In [45]:
n2d_ground = nd_ground[:, :].reshape(-1, 3).astype('float32')
n2d_ground = n2d_ground.reshape(-1, 3, 1)

In [38]:
n2dt_building = nd_building[:, :].reshape(-1, 3).astype('float32')
n2dt_building = n2dt_building.reshape(-1, 3, 1).transpose()

In [39]:
nd_delta = np.subtract(n2dt_building, n2d_ground)

In [47]:
nd_altura = nd_delta[:,2,:]

In [51]:
nd_distancia = np.hypot(nd_delta[:,0,:], nd_delta[:,1,:])

In [54]:
nd_elevacao = np.degrees(np.arctan2(nd_altura, nd_distancia))
nd_elevacao[np.less(nd_elevacao, 0.)] += 360.0

In [56]:
nd_elevacao.shape

(1000, 300792)

In [ ]:
azimute, elevacao = np_coordenadas(nd_building, nd_ground)
print("Distância: ")
print(elevacao.shape)
print(elevacao.size)
print("Elevacao: ")
print(azimute.shape)
print(azimute.size)

In [ ]:
nd_ground.reshape(-1, 3, 1)

In [ ]:
nd_coordenadas = np.stack((azimute, elevacao), axis=1)

In [ ]:
nd_coordenadas

## Calculando o SVF

Agora para calcular o SVF vamos dividir a semi-esfera visível do céu em N fusos, definido pela variável`quantidade_de_fusos`.
E cada um dos fusos terá uma área esférica visível definido pela função `proporcao_visivel_no fuso`.
Depois de disponível essa função vamos iterar ela sobre todos os pontos de ground resultando no retorno da função `proporcao_visivel_total`.

In [ ]:
quantidade_de_fusos = 36