# Fator de Visão de Céu a partir do LiDAR

Podemos também determinar o Fator de Visão de céu, ou Sky View Factor diretamente do LiDAR sem gerar um raster.
Para fins de performance podemos reduzir a densidade de pontos para cerca de 1 metro de resolução e a partir de cada ponto de Ground clacular a coordenada astronômica (Azimute e ALtura) e a distância linear para cada ponto das classes de Edificação e outras feições.

Para esse primeiro teste vamos apenas usar uma folha SCM, sabendo que inerferências para visão de céu podem se estender muito além dos limites das dimensões de uma folha SCM.

In [1]:
import pdal

In [2]:
pipeline="""{
  "pipeline": [
    {
        "type": "readers.las",
        "filename": "arquivos/MDS/MDS_3314-231.laz"
    },
    {
        "type": "filters.sample",
        "radius": 1
    }
  ]
}"""

In [3]:
r = pdal.Pipeline(pipeline)
r.validate()
r.execute()
arrays = r.arrays

In [4]:
len(arrays[0])

471962

In [5]:
arrays[0][732]

(333486.38, 7395559.83, 725.18, 5, 1, 1, 0, 0, 2, -14., 17, 6, 356569.65684247)

In [6]:
#dir(r)
r.schema

{'schema': {'dimensions': [{'name': 'X', 'size': 8, 'type': 'floating'},
   {'name': 'Y', 'size': 8, 'type': 'floating'},
   {'name': 'Z', 'size': 8, 'type': 'floating'},
   {'name': 'Intensity', 'size': 2, 'type': 'unsigned'},
   {'name': 'ReturnNumber', 'size': 1, 'type': 'unsigned'},
   {'name': 'NumberOfReturns', 'size': 1, 'type': 'unsigned'},
   {'name': 'ScanDirectionFlag', 'size': 1, 'type': 'unsigned'},
   {'name': 'EdgeOfFlightLine', 'size': 1, 'type': 'unsigned'},
   {'name': 'Classification', 'size': 1, 'type': 'unsigned'},
   {'name': 'ScanAngleRank', 'size': 4, 'type': 'floating'},
   {'name': 'UserData', 'size': 1, 'type': 'unsigned'},
   {'name': 'PointSourceId', 'size': 2, 'type': 'unsigned'},
   {'name': 'GpsTime', 'size': 8, 'type': 'floating'}]}}

## Importando dados para Pandas

In [7]:
import pandas as pd

In [8]:
df = pd.DataFrame(arrays[0])

In [9]:
df

X           Y       Z  Intensity  ReturnNumber  \
0       333499.29  7395564.35  735.34         18             1   
1       333499.23  7395565.79  735.41         18             1   
2       333499.20  7395566.79  735.25         15             1   
3       333499.15  7395568.21  735.37         14             1   
4       333499.10  7395569.68  735.30         17             1   
...           ...         ...     ...        ...           ...   
471957  333523.36  7395570.78  735.52          2             1   
471958  333521.03  7395570.91  731.07          5             1   
471959  333520.96  7395571.00  732.50          8             1   
471960  333521.09  7395571.84  731.83         18             1   
471961  333520.95  7395571.91  729.86         18             1   

        NumberOfReturns  ScanDirectionFlag  EdgeOfFlightLine  Classification  \
0                     1                  0                 0               6   
1                     1                  0                 0               6   
2                     1                  0                 0               6   
3                     1                  0                 0               6   
4                     1                  0                 0               6   
...                 ...                ...               ...             ...   
471957                2                  1                 0              19   
471958                1                  1                 0               6   
471959                1                  1                 0               6   
471960                1                  1                 0               6   
471961                1                  0                 0               6   

        ScanAngleRank  UserData  PointSourceId        GpsTime  
0               -14.0        17              6  356569.366065  
1               -14.0        17              6  356569.366090  
2               -14.0        17              6  356569.366105  
3               -14.0        17              6  356569.366129  
4               -15.0        17              6  356569.366153  
...               ...       ...            ...            ...  
471957           13.0        40              6  363044.324524  
471958           13.0        40              6  363044.342732  
471959           13.0        40              6  363044.342740  
471960           13.0        40              6  363044.360909  
471961           13.0        40              6  363044.364125  

[471962 rows x 13 columns]

In [10]:
df.Classification.unique()

array([ 6, 20,  2, 19,  5,  9], dtype=uint8)

In [11]:
# filtrando somente os grounds == 2
df[df.Classification == 2]

X           Y       Z  Intensity  ReturnNumber  \
18      333499.25  7395550.72  724.76          6             1   
20      333499.14  7395553.60  724.86          5             1   
26      333498.88  7395560.92  724.87          5             1   
38      333498.72  7395562.04  725.02         36             1   
77      333498.36  7395551.34  724.89         17             1   
...           ...         ...     ...        ...           ...   
471680  333563.96  7395552.14  724.30         15             1   
471723  333558.16  7395554.04  724.33         11             1   
471739  333556.44  7395554.74  724.53          8             1   
471792  333530.38  7395555.62  724.47          6             1   
471830  333561.42  7395560.70  724.59         16             1   

        NumberOfReturns  ScanDirectionFlag  EdgeOfFlightLine  Classification  \
18                    1                  0                 0               2   
20                    1                  0                 0               2   
26                    1                  0                 0               2   
38                    1                  1                 0               2   
77                    1                  0                 0               2   
...                 ...                ...               ...             ...   
471680                1                  0                 0               2   
471723                1                  0                 0               2   
471739                1                  0                 0               2   
471792                1                  0                 0               2   
471830                1                  1                 0               2   

        ScanAngleRank  UserData  PointSourceId        GpsTime  
18              -13.0        17              6  356569.383978  
20              -13.0        17              6  356569.384026  
26              -14.0        17              6  356569.384146  
38              -14.0        17              6  356569.386890  
77              -13.0        17              6  356569.402162  
...               ...       ...            ...            ...  
471680            9.0        40              6  363043.837829  
471723           10.0        40              6  363043.892247  
471739           10.0        40              6  363043.910399  
471792           12.0        40              6  363043.964401  
471830            9.0        40              6  363044.051052  

[15890 rows x 13 columns]

## Calculando o Azimute entre dois pontos

In [25]:
import math

def Az(x1,y1,x2,y2):
    deg = math.degrees(math.atan2((x2 - x1),(y2 - y1)))
    if (deg < 0):
        deg += 360.0
    return deg

In [71]:
Az(1, 1, 1, 0)

180.0

## Calculando a Altura ou Elevação do ponto em relação ao Zenite

In [14]:
from scipy.spatial import distance

In [27]:
## Calculando altura
def altura_graus(x1, y1, z1, x2, y2, z2):
    altura = z2 - z1
    distancia = distance.euclidean([x1, y1], [x2, y2])
    return math.degrees(math.atan2(altura, distancia))
    #return distancia

altura_graus(0,0,0,1,1,1)

35.264389682754654

## Gerando pontos x,y,z 

In [28]:
# Utilizando somente os 10 primeiros registros para fins de performance
df_ground = pd.DataFrame.from_records(df[df.Classification == 2][['X', 'Y', 'Z']].head(100))
#df_ground = df_ground.set_index(['X', 'Y', 'Z'])

In [29]:
df_ground

X           Y       Z
0   333499.25  7395550.72  724.76
1   333499.14  7395553.60  724.86
2   333498.88  7395560.92  724.87
3   333498.72  7395562.04  725.02
4   333498.36  7395551.34  724.89
..        ...         ...     ...
95  333443.95  7395545.15  725.00
96  333443.40  7395540.76  724.61
97  333442.86  7395552.29  724.93
98  333440.83  7395551.85  724.89
99  333440.46  7395541.46  724.92

[100 rows x 3 columns]

In [30]:
df_building = pd.DataFrame.from_records(df[df.Classification == 6][['X', 'Y', 'Z']])
df_building = df_building.rename(columns={'X':'X1', 'Y':'Y1', 'Z':'Z1'})

In [42]:
%timeit df_building.to_numpy() - df_ground.to_numpy()[0, :]

2.83 ms ± 67.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Calculando o Azimute com Matriz de pontos

In [221]:
import numpy as np

def np_az(nd_building, nd_ground):
    delta_x = nd_building[:, 0] - nd_ground[0, 0]
    delta_y = nd_building[:, 1] - nd_ground[0, 1]
    degree = np.arctan2(delta_x, delta_y) * 180 / np.pi
    degree[np.less(degree, 0)] += 360.0
    return degree

In [205]:
## Gerando dados de teste
test_ground = np.array([[0.,0.,0.], [1.,1.,1.]])
test_building = np.array([[0.,2.,2.], [2.,0,2.], [0.,-2.,2.], [-2.,0,18787.], [-2.,9899.,0.1]])

In [206]:
az = np_az(test_building, test_ground)
#df_building.to_numpy()[:, 0] - df_ground.to_numpy()[0, 0]
az

array([  0.        ,  90.        , 180.        , 270.        ,
       359.98842393])

## Calculando a altura/elevação com matriz de pontos

In [226]:
## Calculando altura/elevação

from scipy.spatial import distance

def np_altura(nd_building, nd_ground):
    altura = nd_building[:, 2] - nd_ground[0, 2]
    distancia = np.sqrt(np.sum((nd_building[:, [0,1]] - nd_ground[0, [0,1]])**2, axis=1))
    return np.arctan2((nd_building[:, 2] - nd_ground[0, 2]), distancia) * 180 / np.pi

In [208]:
altura = np_altura(test_building, test_ground)
altura

array([4.50000000e+01, 4.50000000e+01, 4.50000000e+01, 8.99939005e+01,
       5.78803701e-04])

In [209]:
nd_coordenadas = np.array([az, altura])
nd_coordenadas.transpose().shape

(5, 2)

## Utilizando os dados de Building

In [223]:
nd_building = df_building.to_numpy()
nd_ground = df_ground.to_numpy()

In [224]:
def calc_svf(nd_building, nd_ground):
    az = np_az(nd_building, nd_ground)
    altura = np_altura(nd_building, nd_ground)
    coordenadas = np.array([az, altura])
    return coordenadas.transpose()

In [225]:
%timeit calc_svf(nd_building, nd_ground)

34.4 ms ± 235 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Calculando o SVF

Agora para calcular o SVF vamos dividir a semi-esfera visível do céu em N fusos, definido pela variável`quantidade_de_fusos`, e cada um dos fusos terá uma área esférica visível definido pela função `proporcao_visivel_no fuso`.
Depois de disponível essa função vamos iterar ela sobre todos os pontos de ground resultando no retorno da função `proporcao_visivel_total`.

In [227]:
quantidade_de_fusos = 36